# -*- coding: utf-8 -*-
"""Homework 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SYB368HxEJqC3mUB-UpdcCkq6QNqr5XQ

# Deep Dive into Object Detection
"""

def calculate_iou(box1, box2):
    """
    Calculate the Intersection over Union (IoU) of two bounding boxes.
    Box format: [x_min, y_min, x_max, y_max]
    """

    x_left = max(box1[0], box2[0])
    y_top = max(box1[1], box2[1])

    return 0.0

box_A = [50, 50, 150, 150]
box_B = [100, 100, 200, 200]
box_C = [200, 200, 300, 300]

iou_AB = calculate_iou(box_A, box_B)
iou_AC = calculate_iou(box_A, box_C)

print(f"IoU between Box A and Box B: {iou_AB:.3f}")
print(f"IoU between Box A and Box C: {iou_AC:.3f}")

!pip install ultralytics -q
from ultralytics import YOLO

video = '/content/manu_vs_athletic.mp4'

model = YOLO('yolov8n.pt')

print("Processing video...")
results = model.predict(source=video, save=True, conf=0.25)

def calculate_iou(box1, box2):
    """
    Calculate the Intersection over Union (IoU) of two bounding boxes.
    Box format: [x_min, y_min, x_max, y_max]
    """

    x_left = max(box1[0], box2[0])
    y_top = max(box1[1], box2[1])
    x_right = min(box1[2], box2[2])
    y_bottom = min(box1[3], box2[3])

    if x_right < x_left or y_bottom < y_top:
        return 0.0

    intersection_area = (x_right - x_left) * (y_bottom - y_top)

    box1_area = (box1[2] - box1[0]) * (box1[3] - box1[1])
    box2_area = (box2[2] - box2[0]) * (box2[3] - box2[1])

    union_area = box1_area + box2_area - intersection_area

    if union_area == 0:
        return 0.0
    iou = intersection_area / union_area
    return iou

box_A = [50, 50, 150, 150]
box_B = [100, 100, 200, 200]
box_C = [200, 200, 300, 300]

iou_AB = calculate_iou(box_A, box_B)
iou_AC = calculate_iou(box_A, box_C)

print(f"IoU between Box A and Box B: {iou_AB:.3f}")
print(f"IoU between Box A and Box C: {iou_AC:.3f}")

import os

from ultralytics import YOLO

video = '/content/manu_vs_athletic.mp4'

model = YOLO('yolov8n.pt')

print("Processing video...")
results = model.predict(source=video, save=True, conf=0.25)

print("Installing...")
!pip install ultralytics -q
print("Installed.")

import os

from ultralytics import YOLO

video = '/content/manu_vs_athletic.mp4'

model = YOLO('yolov8n.pt')

print("Processing video...")
results = model.predict(source=video, save=True, conf=0.25)

import os

from ultralytics import YOLO

video = '/content/manu_vs_athletic.mp4'

model = YOLO('yolov8n.pt')

print("Processing video...")
results = model.predict(source=video, save=True, conf=0.25)

!ls -F runs/detect/predict/

import os

from ultralytics import YOLO

video = '/content/manu_vs_athletic.mp4'

model = YOLO('yolov8n.pt')

print("Processing video...")
results = model.predict(source=video, save=True, conf=0.25)

print("...")
!apt-get update -qq
!apt-get install -y ffmpeg

import os

from ultralytics import YOLO

video = '/content/manu_vs_athletic.mp4'

model = YOLO('yolov8n.pt')

print("Processing video...")
results = model.predict(source=video, save=True, conf=0.25)

!pip install ultralytics --upgrade -q

import os

from ultralytics import YOLO

video = '/content/manu_vs_athletic.mp4'

model = YOLO('yolov8n.pt')

print("Processing video...")
results = model.predict(source=video, save=True, conf=0.25)

import os

!pip install ultralytics opencv-python --upgrade -q

from ultralytics import YOLO

video = '/content/manu_vs_athletic.mp4'

model = YOLO('yolov8n.pt')

results = model.predict(source=video, save=True, conf=0.25)

import os
import cv2

!pip install ultralytics opencv-python --upgrade -q

video_path = '/content/manu_vs_athletic.mp4'
cap = cv2.VideoCapture(video_path)
if not cap.isOpened():
    print(f"[DIAGNOSTIC ERROR] OpenCV FAILED to open video: {video_path}.")

    raise FileNotFoundError(f"Could not open video: {video_path}")
else:
    print(f"[DIAGNOSTIC SUCCESS] Successfully opened video: {video_path}. Proceeding with YOLO inference.")
    cap.release()

from ultralytics import YOLO

video = '/content/manu_vs_athletic.mp4'

model = YOLO('yolov8n.pt')

results = model.predict(source=video, save=True, conf=0.25)

import os

from ultralytics import YOLO

video = '/content/manu_vs_athletic.mp4'

model = YOLO('yolov8n.pt')

results = model.predict(source=video, save=True, conf=0.25)

import os

from ultralytics import YOLO

video = '/content/manu_vs_athletic.mp4'

model = YOLO('yolov8n.pt')
results = model.predict(source=video, save=True, conf=0.25, stream=True)

import os
from ultralytics import YOLO

video = '/content/manu_vs_athletic.mp4'

model = YOLO('yolov8s.pt')

results = model.predict(source=video, save=True, conf=0.5, iou=0.5, stream=True)

!ls -F runs/detect/predict/